Remove build_number_label

diff --git a/.github/workflows/generate-release-notes.yml b/.github/workflows/generate-release-notes.yml
--- a/.github/workflows/generate-release-notes.yml
+++ b/.github/workflows/generate-release-notes.yml
@@ -3,10 +3,6 @@ name: 'Generate release notes'
 on:
   workflow_dispatch:
     inputs:
-      build_number_label:
-        description: 'Build number label, must be set if this is for a preview build.'
-        required: false
-        type: string
       last_release_tag:
         description: 'The release tag to use as a baseline. If left empty, this will be set as the last tag on the branch.'
         required: false
@@ -45,30 +41,33 @@ jobs:
           release_version=$(perl -ne '/<VersionPrefix>([^<]*)/ && print $1' $versionFile)
           release_version_label=$(perl -ne '/<PreReleaseVersionLabel>([^<]*)/ && print $1' $versionFile)
           release_version_iteration=$(perl -ne '/<PreReleaseVersionIteration>([^<]*)/ && print $1' $versionFile)
+          major_minor_version=${release_version%.*}
+
+          version_url="https://aka.ms/dotnet/diagnostics/monitor${major_minor_version}/release/dotnet-monitor.nupkg.version"
+          qualified_release_version=$(curl -sL $version_url)
+          # Check if the aka.ms url existed
+          if [[ "$qualified_release_version" =~ "<html" || -z "$qualified_release_version" ]]; then
+            echo "Could not determine qualified release version, $version_url did not contain the expected information"
+            exit 1
+          fi
+
+          # trim the return carriage
+          qualified_release_version=$(echo $qualified_release_version | tr -d '\r')
 
           friendly_release_name=""
-          qualified_release_version=""
 
           if [ "$release_version_label" == "rtm" ] || [ "$release_version_label" == "servicing" ]; then
             friendly_release_name="$release_version build"
-            qualified_release_version="$release_version"
-          elif [ -z "$build_number_label" ]; then
-              echo "build_number_label is not set!"
-              exit 1
+          elif [ "$release_version_label" == "rc" ]; then
+            friendly_release_name="official $release_version Release Candidate"
           else
-            qualified_release_version="${release_version}-${release_version_label}.${release_version_iteration}.${build_number_label}"
-            if [ "$release_version_label" == "rc" ]; then
-              friendly_release_name="official $release_version Release Candidate"
-            else
-              friendly_release_name="next official preview version"
-            fi
+            friendly_release_name="next official preview version"
           fi
 
           echo "release_note_path=$(echo ./documentation/releaseNotes/releaseNotes.v${qualified_release_version}.md)" >> $GITHUB_ENV
           echo "friendly_release_name=$(echo ${friendly_release_name})" >> $GITHUB_ENV
           echo "qualified_release_version=$(echo ${qualified_release_version})" >> $GITHUB_ENV
         env:
-          build_number_label: ${{ inputs.build_number_label }}
           last_release_tag: ${{ inputs.last_release_tag }}
 
       - name: Checkout main
